homework8/problem1/config/routes.rb
Rails.application.routes.draw do
  
  root('users#index')
  devise_for :users
  resources :users
  resources :hotels
  
end

homework8/problem1/app/models/hotel.rb
class Hotel < ActiveRecord::Base
	belongs_to(:user)
end

homework8/problem1/app/models/user.rb
class User < ActiveRecord::Base
	has_many(:hotels)
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

homework8/problem1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

homework8/problem1/app/controllers/hotels_controller.rb
class HotelsController < ApplicationController

	def index
		@hotels = Hotel.all
	end

	def new
		@hotel = Hotel.new
	end 

	def create 
		
		@hotels = current_user.hotels.create(hotel_params)
	end

	def edit
		@hotel = Hotel.find(params[:id])
	end
	def update
		@hotel.update(hotel_params)
	end

	private 

	def hotel_params
		params[:hotel].permit(:name, :description, :location, :photo)
	end

end

homework8/problem1/app/controllers/users_controller.rb
class UsersController <  ApplicationController 
	
	before_action(:authenticate_user!, only: [:index, :show, :edit])

	def index
		@users = User.all
	end

	def show
		
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
		if current_user.admin? ||  current_user.id == @user.id
			get_user
		else
			redirect_to(action: :index )	
		end
		
	end

	def update
		get_user
		@user.update(user_params)
		redirect_to_user_if_valid(:edit, 'The user was sucessfully updated', 'please complete all field')
	end


	private

	def redirect_to_user_if_valid(action_to_render, success_copy, failure_copy)
		if @user.valid?
			flash.notice = success_copy
			redirect_to(@user)
		else
			flash.now.alert = failure_copy
			render(action_to_render)
		end	
	end

	def get_user
		@user = User.find(params[:id])
	end

	def user_params
		params[:user].permit(:email, :name, :headline, :profile, :admin)
	end
end

homework8/problem1/app/helpers/application_helper.rb
module ApplicationHelper
end

homework8/problem1/app/views/hotels/edit.html.erb
<h1>Edit This Hotel</h1>

<%= form_for(@hotel, html: {multipart: true}) do |f| %>
	<div class="form-group">
<div>
<%= f.label(:name) %>
<%= f.text_field(:name) %>
</div>
<div>
<%= f.label(:location) %>
<%= f.text_field(:location) %>
</div>
<div>
<%= f.label(:description) %>
<%= f.text_area(:description) %>	
</div>
<div>
<%= f.label(:photo) %>
<%= f.file_field(:photo) %>	
</div>
<div> <%= f.submit %></div>

<% end %>

homework8/problem1/app/views/hotels/index.html.erb
<h1>All Hotels</h1>
<ul>
	<%@hotels.each do |hotel| %>
	<li>Hotel Name: <%= link_to(hotel.name, hotel_path(hotel)) %> </li> <p>Description: <%= hotel.description %></p>
	
	<% end %>
</ul>

homework8/problem1/app/views/hotels/new.html.erb
<h1>Add a new hotel</h1>

<%= form_for(@hotel, html: {multipart: true}) do |f| %>
	<div class="form-group">
<div>
<%= f.label(:name) %>
<%= f.text_field(:name) %>
</div>
<div>
<%= f.label(:location) %>
<%= f.text_field(:location) %>
</div>
<div>
<%= f.label(:description) %>
<%= f.text_area(:description) %>	
</div>
<div>
<%= f.label(:photo) %>
<%= f.file_field(:photo) %>	
</div>
<div> <%= f.submit %></div>

<% end %>

homework8/problem1/app/views/users/edit.html.erb
<h1>Edit This User</h1>
<% if @user.errors.any? %>
<ul>
<%@user.errors.full_messages.each do |error|%>
 		<li><%= error %></li>
 <%end %> 
 </ul>
 <% end %>
<%= form_for(@user, html: {multipart: true}) do |f| %>
<p>
<%= f.label(:email) %>
<%= f.text_field(:email) %>
</p>
<p>
<%= f.label(:name) %>
<%= f.text_field(:name) %>
</p>
<p>
<%= f.label(:headline) %>
<%= f.text_field(:headline) %>	
</p>
<p>
<%= f.label(:profile) %>
<%= f.text_area(:profile) %>	
</p>
<p>
<% if current_user.admin? %>
	<%= f.label(:admin) %>
	<%= f.text_area(:admin) %>
<% end %>
</p>
<p> <%= f.submit %></p>

<% end %>

homework8/problem1/app/views/users/index.html.erb
<h1>All Users</h1>
<ul>
	<%@users.each do |user| %>
	<li>Name: <%= link_to(user.name, user_path(user)) %> </li> <p>Headline: <%= user.headline %></p>
	
	<% end %>
</ul>

homework8/problem1/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

homework8/problem1/app/views/users/show.html.erb
<h1>User Profile</h1>
<p> ID: <%=@user.id %> </p>
<p> EMAIL: <%=@user.email %> </p>
<p> NAME: <%=@user.name %> </p>
<p> HEADLINE: <%=@user.headline %> </p>
<p> PROFILE: <%=@user.profile %> </p>
<% if current_user.admin? == true %>
	<p> ADMIN: <%=@user.admin %> </p>
<% end %>
<% if (user_signed_in?) && (current_user.admin? || current_user == @user) %>
	<%= link_to('Edit User', edit_user_path) %>
	<%= link_to('Add a new Hotel', new_hotel_path) %>
	<%= link_to('edit a Hotel', edit_hotel_path) %>
<% else %>
<% end %>