homework6/problem1/s/config/routes.rb
Rails.application.routes.draw do
  root('posts#index')
  resources(:posts)
end

homework6/problem1/s/app/models/address.rb
class Address < ActiveRecord::Base
	has_many(:users)
end

homework6/problem1/s/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to(:user)
end

homework6/problem1/s/app/models/user.rb
class User < ActiveRecord::Base
	has_many(:addresses)
	has_many(:posts)
end

homework6/problem1/s/app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def new 
		@post = Post.new
	end

	def show
		get_post
	end

	def index
		@posts = Post.all
	end

	def create 
		@post = Post.create(post_params)
	end

	def edit
		get_post
	end 

	def update
		get_post
		@post.update(post_params)
	end 

	private 

	def get_post
		@post = Post.find(params[:id])
	end

	def post_params
		params[:post].permit(:title, :body, :image)
	end
end	

homework6/problem1/s/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>S</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav>
			<p> <a> <%= link_to("All Posts", posts_path) %> </a></p>
			<p> <a> <%= link_to("New Post", new_post_path) %> </a></p>
			
	</nav>

<%= yield %>

</body>
</html>

homework6/problem1/s/app/views/posts/create.html.erb
<h1>Here is your new post</h1>
<p> Title: <%= @post.title %> </p>
<p> Body: <%= @post.body %> </p>
</p> Edit: <%= link_to('Edit this post', edit_post_path(@post)) %> </p>
<p>Good Job</p>

homework6/problem1/s/app/views/posts/edit.html.erb
<h1>Edit This Post</h1>

<%= form_for(@post) do |f| %>
<p>
<%= f.label(:title) %>
<%= f.text_field(:title) %>
</p>
<p>
<%= f.label(:body) %>
<%= f.text_area(:body) %>	
</p>
<p>
<%= f.label(:image) %>
<%= f.text_area(:image) %>	
</p>
<p> <%= f.submit %></p>

<% end %>

homework6/problem1/s/app/views/posts/index.html.erb
<h1>All Posts</h1>

<p>Click on the title to see full post.</p>
<ul>
	<%@posts.each do |post| %>
	<li> Title: <%= link_to(post.title, post_path(post)) %></li>
	<% end %>
</ul>	

homework6/problem1/s/app/views/posts/new.html.erb
<h1>Start a new Post</h1>

<%= form_for(@post) do |f| %>
<p>
<%= f.label(:title) %>
<%= f.text_field(:title) %>
</p>
<p>
<%= f.label(:body) %>
<%= f.text_area(:body) %>	
</p>
<p>
<%= f.label(:image) %>
<%= f.text_area(:image) %>	
</p>
<p> <%= f.submit %></p>

<% end %>

homework6/problem1/s/app/views/posts/show.html.erb
<h1>Show Full Post</h1>
<p> Title: <%= @post.title %> </p>
<p> Body: <%= @post.body %> </p>
</p> Edit: <%= link_to('Edit this post', edit_post_path(@post)) %> </p>
<p>Good Job</p>

homework6/problem1/s/app/views/posts/update.html.erb
<h1>Your Post was updated succesfully</h1>

<p> ID: <%= @post.id %> </p>
<p> Title: <%= @post.title %> </p>
<p> Body: <%= @post.body %> </p>
<p> Image: <%= @post.image %> </p>
</p> Edit: <%= link_to('Edit this post', edit_post_path(@post)) %> </p>
<p>Good Job</p>