homework7/problem1/config/routes.rb
Rails.application.routes.draw do
  
  root('users#index')
  devise_for :users
  resources :users
  
end

homework7/problem1/app/models/user.rb
class User < ActiveRecord::Base
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

homework7/problem1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Problem1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>	
	<nav>
			<p> <a> <%= link_to("All Users", users_path) %> </a></p>
			


			<% if user_signed_in?%>
				<p>You are logged in as <%= current_user.email %></p>
				<p><%= link_to('Your Profile',current_user) %></p>
				<p><%= link_to('LOG OUT', destroy_user_session_path, method: :delete) %></p>
			<% else %>
			<p> <a> <%= link_to("Log In", user_session_path) %> </a></p>
			<p> <a> <%= link_to("SIGN UP", new_user_registration_path) %> </a></p>
			<% end %>


		</nav>


	<% if flash.notice %>
			<div class="notice"><%= flash.notice %></div>
		<% end %>
		<% if flash.alert %>
			<div class="notice"><%= flash.alert %></div>
		<% end %>
<%= yield %>

</body>
</html>

homework7/problem1/app/views/users/show.html.erb
<h1>User Profile</h1>
<p> ID: <%=@user.id %> </p>
<p> EMAIL: <%=@user.email %> </p>
<p> NAME: <%=@user.name %> </p>
<p> HEADLINE: <%=@user.headline %> </p>
<p> PROFILE: <%=@user.profile %> </p>
<% if current_user.admin? == true %>
	<p> ADMIN: <%=@user.admin %> </p>
<% end %>
<% if (user_signed_in?) && (current_user.admin? || current_user == @user) %>
	<%= link_to('Edit User', edit_user_path) %>
<% else %>
<% end %>